name = "KitePowerDesignTools"
uuid = "36584951-25a7-433d-a50f-90315ae9eddf"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "1.0.0-DEV"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
YAML = "0.4.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
