name = "KitePowerDesignTools"
uuid = "36584951-25a7-433d-a50f-90315ae9eddf"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
